export const CASTLE_DEFAULTS = {
  partner1Name: "Sofia",
  partner2Name: "",
  welcomeText: "Cu bucurie vă invităm",
  celebrationText: "botezului",
  eventType: "baptism",
  weddingDate: "",
  showWelcomeText: true,
  showCelebrationText: true,
  showCountdown: true,
  showTimeline: false,
  showGodparents: true,
  showRsvpButton: true,
  showCivil: false,
  showChurch: true,
  showVenue: true,
  churchLabel: "Botezul",
  venueLabel: "Petrecerea",
  civilLabel: "Cununie Civilă",
  civilTime: "10:00",
  churchTime: "11:00",
  eventTime: "14:00",
  civilLocationName: "Primăria",
  civilLocationAddress: "Strada Principală 1, București",
  churchLocationName: "Biserica Sfânta Maria",
  churchLocationAddress: "Strada Bisericii 5, București",
  locationName: "Salon Unicorn",
  locationAddress: "Strada Magică 1, București",
  civilWazeLink: "",
  churchWazeLink: "",
  venueWazeLink: "",
  godparents: JSON.stringify([{ godfather: "Nume Naș", godmother: "Nume Nașă" }]),
  timeline: JSON.stringify([]),
  colorTheme: "magic",
  rsvpButtonText: "Confirmă Prezența",
};

export const CASTLE_DEFAULT_BLOCKS: InvitationBlock[] = [
  {
    id: "def-photo-1",
    type: "photo" as const,
    show: true,
    imageData: "/unicornacademy/sophia.jpg",
    altText: "Sophia",
    aspectRatio: "3:4" as const,
    photoClip: "arch" as const,
    photoMasks: ["fade-b"] as any,
  },
  {
    id: "def-text-1",
    type: "text" as const,
    show: true,
    content: "Te așteptăm cu drag să fim împreună în această zi magică.",
  },
  {
    id: "def-family-1",
    type: "family" as const,
    show: true,
    label: "Părinții",
    content: "Cu drag și recunoștință",
    members: JSON.stringify([{ name1: "Mama", name2: "Tata" }]),
  },
  {
    id: "def-family-2",
    type: "family" as const,
    show: true,
    label: "Nașii",
    content: "Cu drag și recunoștință",
    members: JSON.stringify([{ name1: "Nașa", name2: "Nașul" }]),
  },
  {
    id: "def-calendar",
    type: "calendar" as const,
    show: true,
  },
  {
    id: "def-countdown",
    type: "countdown" as const,
    show: true,
    countdownTitle: "Timp rămas până la eveniment",
  },
  { id: "def-divider-1", type: "divider" as const, show: true },
  {
    id: "def-location-1",
    type: "location" as const,
    show: true,
    label: "Ceremonia",
    time: "11:00",
    locationName: "Biserica Sfânta Maria",
    locationAddress: "Strada Bisericii 5, București",
    wazeLink: "",
  },
  {
    id: "def-location-2",
    type: "location" as const,
    show: true,
    label: "Petrecerea",
    time: "14:00",
    locationName: "Salon Unicorn",
    locationAddress: "Strada Magică 1, București",
    wazeLink: "",
  },
  {
    id: "def-text-2",
    type: "text" as const,
    show: true,
    content: "O piesă de suflet, aleasă cu drag pentru această zi de neuitat.",
  },
  {
    id: "def-music",
    type: "music" as const,
    show: true,
    musicTitle: "",
    musicArtist: "",
    musicUrl: "",
    musicType: "none" as const,
  },
  {
    id: "def-photo-2",
    type: "photo" as const,
    show: true,
    imageData: "/unicornacademy/wildstar.jpg",
    altText: "Wildstar",
    aspectRatio: "1:1" as const,
    photoClip: "circle" as const,
    photoMasks: [] as any,
  },
  {
    id: "def-text-3",
    type: "text" as const,
    show: true,
    content: "Ne-ar bucura să ne confirmați prezența pentru o bună organizare a evenimentului.",
  },
  {
    id: "def-rsvp",
    type: "rsvp" as const,
    show: true,
    label: "Confirmă Prezența",
  },
];

export const CASTLE_PREVIEW_DATA = {
  guest: { name: "Invitat Drag", status: "pending", type: "adult" },
  project: { selectedTemplate: "unicorn-academy" },
  profile: {
    ...CASTLE_DEFAULTS,
    weddingDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    customSections: JSON.stringify(CASTLE_DEFAULT_BLOCKS),
  },
};

export default UnicornAcademyTemplate;
